// SPDX-License-Identifier: GPL-3.0-or-later
//
// The long tail, through whatever FFmpeg the machine already has.
//
// FFmpeg is the one dependency this tree does not vendor, and the reasons are
// concrete: its configure is a shell script needing MSYS2 and nasm on Windows,
// its build is tens of minutes, its output is tens of megabytes, and **whether
// it is LGPL or GPL is a choice that belongs to whoever installs it**. So this
// module finds it at run time and reports itself unable when it is absent, which
// is the behaviour the architecture already has for a module nobody installed.
//
// It talks to `ffprobe` and `ffmpeg` as programs rather than linking libavcodec,
// and that is deliberate rather than lazy. FFmpeg's public structs -- AVFrame,
// AVCodecContext, AVStream -- change layout between major versions, so resolving
// the symbols out of a DLL still leaves the struct layouts to get right, and the
// headers that describe them cannot be vendored on their own because `avconfig.h`
// is generated by configure. Going through the executables costs a process per
// file and buys immunity from all of that: this works against FFmpeg 4 through 8
// without being rebuilt.
//
// Bit-exactness is unaffected and is checked the same way as everywhere else:
// the raw format asked for is the decoder's own native one, and the bytes are
// hashed against a reference. See docs/formats.md.
//
// **It is a demuxer that decodes for itself, and the flag says so.** FFmpeg is
// not a container reader that happens to decode; it is a pipeline with a file at
// one end and PCM at the other, and there is no seam in it that this tree could
// take hold of. MP_STREAM_SELF_DECODES is that stated rather than disguised: one
// structure with one declared exception, instead of a module pretending to be
// two things it cannot be separated into.
//
// What the v2 shape did buy here is real, though, and it is streams. `ffprobe`
// enumerates every audio stream in a file and this module used to ask for `a:0`
// and throw the rest away -- so a film with a commentary track had one track as
// far as MediaPerch was concerned. Now each one is described and `select` picks
// between them.

#include <mediaperch/module.h>

#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <windows.h>

#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace {

const MpHost* g_host = nullptr;
std::wstring g_ffmpeg;
std::wstring g_ffprobe;

void log(MpLogLevel level, const char* message) noexcept
{
    if (g_host != nullptr && g_host->log != nullptr) {
        g_host->log(g_host->ctx, level, message);
    }
}

void log_fmt(MpLogLevel level, const char* format, ...) noexcept
{
    char buffer[1024];
    va_list args;
    va_start(args, format);
    std::vsnprintf(buffer, sizeof(buffer), format, args);
    va_end(args);
    log(level, buffer);
}

std::wstring widen(const char* utf8)
{
    if (utf8 == nullptr || *utf8 == '\0') {
        return {};
    }
    const int needed = ::MultiByteToWideChar(CP_UTF8, 0, utf8, -1, nullptr, 0);
    if (needed <= 1) {
        return {};
    }
    std::wstring out(static_cast<std::size_t>(needed - 1), L'\0');
    ::MultiByteToWideChar(CP_UTF8, 0, utf8, -1, out.data(), needed);
    return out;
}

std::string narrow(const std::wstring& wide)
{
    if (wide.empty()) {
        return {};
    }
    const int needed = ::WideCharToMultiByte(CP_UTF8, 0, wide.c_str(), -1, nullptr, 0,
                                             nullptr, nullptr);
    if (needed <= 1) {
        return {};
    }
    std::string out(static_cast<std::size_t>(needed - 1), '\0');
    ::WideCharToMultiByte(CP_UTF8, 0, wide.c_str(), -1, out.data(), needed, nullptr,
                          nullptr);
    return out;
}

/// Beside this module first, then wherever PATH says. Beside first so that an
/// install can ship a known FFmpeg without changing the machine's.
std::wstring find_program(const wchar_t* name)
{
    wchar_t module_path[MAX_PATH * 2]{};
    HMODULE self = nullptr;
    ::GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                             GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                         reinterpret_cast<LPCWSTR>(&find_program), &self);
    if (::GetModuleFileNameW(self, module_path, static_cast<DWORD>(std::size(module_path)))
        != 0) {
        std::wstring beside{module_path};
        const std::size_t slash = beside.find_last_of(L"\\/");
        if (slash != std::wstring::npos) {
            beside.resize(slash + 1);
            beside += name;
            if (::GetFileAttributesW(beside.c_str()) != INVALID_FILE_ATTRIBUTES) {
                return beside;
            }
        }
    }

    wchar_t found[MAX_PATH * 2]{};
    wchar_t* leaf = nullptr;
    const DWORD n = ::SearchPathW(nullptr, name, nullptr,
                                  static_cast<DWORD>(std::size(found)), found, &leaf);
    return (n != 0 && n < std::size(found)) ? std::wstring{found} : std::wstring{};
}

/// A child process whose stdout we read. stderr goes nowhere: FFmpeg writes
/// progress there and none of it is ours to interpret.
class Child {
public:
    Child() = default;
    ~Child() { close(); }
    Child(const Child&) = delete;
    Child& operator=(const Child&) = delete;
    Child(Child&&) = delete;
    Child& operator=(Child&&) = delete;

    bool start(const std::wstring& command_line)
    {
        close();

        SECURITY_ATTRIBUTES inheritable{};
        inheritable.nLength = sizeof(inheritable);
        inheritable.bInheritHandle = TRUE;

        HANDLE read_end = nullptr;
        HANDLE write_end = nullptr;
        if (::CreatePipe(&read_end, &write_end, &inheritable, 1 << 20) == 0) {
            return false;
        }
        // The read end must not travel into the child, or the pipe never reports
        // end-of-file because this process still holds a writer.
        ::SetHandleInformation(read_end, HANDLE_FLAG_INHERIT, 0);

        STARTUPINFOW startup{};
        startup.cb = sizeof(startup);
        startup.dwFlags = STARTF_USESTDHANDLES;
        startup.hStdOutput = write_end;
        startup.hStdError = ::GetStdHandle(STD_ERROR_HANDLE);
        startup.hStdInput = nullptr;

        PROCESS_INFORMATION process{};
        std::wstring mutable_command = command_line; // CreateProcessW may write to it
        const BOOL ok = ::CreateProcessW(nullptr, mutable_command.data(), nullptr, nullptr,
                                         TRUE, CREATE_NO_WINDOW, nullptr, nullptr,
                                         &startup, &process);
        ::CloseHandle(write_end);
        if (ok == 0) {
            ::CloseHandle(read_end);
            return false;
        }

        ::CloseHandle(process.hThread);
        process_ = process.hProcess;
        stdout_ = read_end;
        return true;
    }

    /// Blocks until `bytes` are read or the child closes its end.
    std::size_t read(void* dst, std::size_t bytes)
    {
        auto* out = static_cast<std::uint8_t*>(dst);
        std::size_t total = 0;
        while (total < bytes) {
            DWORD got = 0;
            const DWORD want =
                static_cast<DWORD>(bytes - total < (1u << 20) ? bytes - total : (1u << 20));
            if (::ReadFile(stdout_, out + total, want, &got, nullptr) == 0 || got == 0) {
                break;
            }
            total += got;
        }
        return total;
    }

    void close() noexcept
    {
        if (process_ != nullptr) {
            // Stopping mid-file is the normal case: the graph is done with the
            // track. Waiting for FFmpeg to finish decoding the rest of an album
            // side would be the strange behaviour.
            ::TerminateProcess(process_, 0);
            ::WaitForSingleObject(process_, 2000);
            ::CloseHandle(process_);
            process_ = nullptr;
        }
        if (stdout_ != nullptr) {
            ::CloseHandle(stdout_);
            stdout_ = nullptr;
        }
    }

    [[nodiscard]] bool running() const noexcept { return stdout_ != nullptr; }

private:
    HANDLE process_ = nullptr;
    HANDLE stdout_ = nullptr;
};

/// Runs a program to completion and returns everything it wrote to stdout.
std::string capture(const std::wstring& command_line)
{
    Child child;
    if (!child.start(command_line)) {
        return {};
    }
    std::string out;
    std::vector<char> chunk(64 * 1024);
    for (;;) {
        const std::size_t got = child.read(chunk.data(), chunk.size());
        if (got == 0) {
            break;
        }
        out.append(chunk.data(), got);
    }
    return out;
}

std::wstring quoted(const std::wstring& path)
{
    return L"\"" + path + L"\"";
}

/// ffprobe's `key=value` output, which exists precisely so that nobody has to
/// put a JSON parser in a decoder module.
std::string field(const std::string& text, const char* key)
{
    const std::string needle = std::string{key} + "=";
    std::size_t at = 0;
    while ((at = text.find(needle, at)) != std::string::npos) {
        const bool at_line_start = at == 0 || text[at - 1] == '\n' || text[at - 1] == '\r';
        if (at_line_start) {
            const std::size_t from = at + needle.size();
            const std::size_t to = text.find_first_of("\r\n", from);
            return text.substr(from, to == std::string::npos ? std::string::npos
                                                             : to - from);
        }
        at += needle.size();
    }
    return {};
}

/// ffprobe's per-stream blocks, split apart so `field` can be asked about one
/// stream at a time. With several audio tracks the keys repeat, and a reader
/// that searched the whole output would answer every question with track zero.
std::vector<std::string> stream_blocks(const std::string& text)
{
    std::vector<std::string> blocks;
    std::size_t at = 0;
    for (;;) {
        const std::size_t begin = text.find("[STREAM]", at);
        if (begin == std::string::npos) {
            break;
        }
        const std::size_t end = text.find("[/STREAM]", begin);
        blocks.push_back(text.substr(begin, end == std::string::npos ? std::string::npos
                                                                    : end - begin));
        if (end == std::string::npos) {
            break;
        }
        at = end + 1;
    }
    return blocks;
}

bool magic(const std::uint8_t* head, std::size_t bytes, const char* what,
           std::size_t offset = 0)
{
    const std::size_t n = std::strlen(what);
    return bytes >= offset + n && std::memcmp(head + offset, what, n) == 0;
}

} // namespace

/// One audio stream, as ffprobe described it.
struct Stream {
    MpFormat format{};
    std::uint32_t frame_bytes = 0;
    std::uint64_t total_frames = 0;
    /// The raw muxer FFmpeg is asked for: exactly the decoder's own sample
    /// format, so that nothing in the chain converts.
    std::wstring raw_format;
};

struct MpDemux {
    std::wstring path;
    std::vector<Stream> streams;
    std::size_t selected = 0;

    Child child;
    std::uint64_t position = 0;
    bool ended = false;
    bool started = false;

    [[nodiscard]] const Stream& current() const { return streams[selected]; }
};

namespace {

bool start_at(MpDemux* d, std::uint64_t frame)
{
    const Stream& stream = d->current();
    // -ss after -i is the sample-accurate form. The other one, before -i, seeks
    // by container index and lands on a packet boundary, which is faster and
    // wrong for a player that reports positions in frames.
    std::wstring command = quoted(g_ffmpeg) + L" -v error -nostdin -i " + quoted(d->path);
    if (frame != 0) {
        const double seconds = static_cast<double>(frame) / stream.format.sample_rate;
        wchar_t at[64]{};
        std::swprintf(at, std::size(at), L" -ss %.9f", seconds);
        command += at;
    }
    // The stream that was selected, rather than "the first audio track" -- which
    // is the whole of what enumerating them was for.
    wchar_t map[32]{};
    std::swprintf(map, std::size(map), L" -map 0:a:%u ", static_cast<unsigned>(d->selected));
    command += map;
    command += L"-f " + stream.raw_format + L" -";

    d->position = frame;
    d->ended = false;
    d->started = true;
    return d->child.start(command);
}

MpResult MP_CALL demux_probe(const char* path, const std::uint8_t* head, std::size_t bytes,
                               std::uint32_t* out_score) noexcept
{
    if (out_score == nullptr) {
        return MP_ERR_INVALID;
    }
    (void)path;
    *out_score = 0;
    if (head == nullptr || g_ffprobe.empty()) {
        return MP_OK; // nothing installed to decode with
    }

    // The formats nothing else in this tree reads. Scored at 100 because for
    // these it is the only answer; everything else gets 30, so it stays the
    // fallback rather than taking work from a decoder that does it better.
    //
    // "OggS" is the one entry that is no longer strictly true: decode_ogg reads
    // Vorbis and Opus now. It stays at 100 because it is still the only answer
    // for the *rest* of Ogg -- OggFLAC, Speex -- and because the tie against
    // decode_ogg's 100 is broken by priority, 110 to 60, in decode_ogg's favour.
    // Scoring by codec instead would mean parsing the identification header
    // here to reach the same outcome.
    static const struct {
        const char* bytes;
        std::size_t at;
    } only_here[] = {
        {"OggS", 0},                     // OggFLAC and Speex; decode_ogg outranks
                                         // this for Vorbis and Opus
        {"MAC ", 0},                     // Monkey's Audio
        {"wvpk", 0},                     // WavPack
        {"\x1A\x45\xDF\xA3", 0},         // Matroska, WebM
        {"DSD ", 0},                     // DSF
        {"FRM8", 0},                     // DFF
        {"TTA1", 0},                     // True Audio
        {"MPCK", 0},                     // Musepack
        {"caff", 0},                     // Core Audio Format
        // Added after `mediaperch-probe claims` was asked about a spread of
        // containers and found these had **no claimant at all** -- files this
        // module reads perfectly, refused by the whole tree because its probe
        // is a magic table and these were not in it. The alternative to a table
        // is running `ffprobe` on every candidate, which is a process per file
        // per probe; the table is the right shape and was simply short.
        {"\x0B\x77", 0},                 // AC-3, and E-AC-3, which share a sync
        {"\x7F\xFE\x80\x01", 0},        // DTS, 16-bit big-endian
        {"\xFE\x7F\x01\x80", 0},        // DTS, 16-bit little-endian
        {"#!AMR", 0},                    // AMR-NB and AMR-WB
        {"FLV", 0},                      // Flash video, which carries MP3 and AAC
        {"ajkg", 0},                     // Shorten
        {"tBaK", 0},                     // TAK
        {"OFR ", 0},                     // OptimFROG
    };

    // MPEG-TS is the one that cannot be a magic string: its marker is a 0x47
    // byte every 188 bytes, which is a pattern rather than a prefix. Three in a
    // row is enough to tell it from a file that merely starts with a 'G'.
    if (bytes >= 3 * 188 + 1 && head[0] == 0x47u && head[188] == 0x47u &&
        head[2 * 188] == 0x47u && head[3 * 188] == 0x47u) {
        *out_score = 100;
        return MP_OK;
    }

    for (const auto& candidate : only_here) {
        if (magic(head, bytes, candidate.bytes, candidate.at)) {
            *out_score = 100;
            return MP_OK;
        }
    }
    // MP4 is the one place this module stops being a fallback.
    //
    // Measured: for AAC, FFmpeg returns exactly the length the file claims and
    // starts at frame zero, while Media Foundation starts 1024 frames -- 21.3 ms
    // -- late, leaves the encoder padding on the end, refuses 8 kHz outright and
    // refuses 7.1 outright. That is a correctness difference rather than a
    // preference, so MP4 audio goes to FFmpeg wherever FFmpeg is installed.
    //
    // decode_alac still wins an ALAC file: it scores the same 100 and outranks
    // this module on priority, and it declines anything that is not ALAC in two
    // seeks. Media Foundation is what is left when FFmpeg is absent.
    if (magic(head, bytes, "ftyp", 4)) {
        *out_score = 100;
        return MP_OK;
    }
    // ASF, which is WMA's container. At the fallback score rather than 100:
    // `decode_mf` claims it at 100 and should keep it on Windows, where the OS
    // decoder is the one that was written for the format. What this buys is a
    // machine with no Media Foundation -- the Linux head, one day -- where a
    // WMA would otherwise be a file nothing claims at all. The format matrix
    // is what noticed: FFmpeg read the file when it was forced to and scored
    // zero on it, which is a gap rather than a policy.
    static const char asf[] = "\x30\x26\xB2\x75\x8E\x66\xCF\x11";
    if (magic(head, bytes, "ID3") ||
        magic(head, bytes, "fLaC") || magic(head, bytes, "RIFF") ||
        magic(head, bytes, asf) ||
        (bytes >= 2 && head[0] == 0xFF && (head[1] & 0xE0) == 0xE0)) {
        *out_score = 30;
    }
    return MP_OK;
}

/// Describes one audio stream from its ffprobe block, or refuses it.
bool describe(const std::string& block, const char* path, Stream& out)
{
    const std::string rate_text = field(block, "sample_rate");
    const std::string channels_text = field(block, "channels");
    const std::string sample_fmt = field(block, "sample_fmt");
    const std::string raw_bits_text = field(block, "bits_per_raw_sample");
    const std::string duration_text = field(block, "duration");

    const auto rate = static_cast<std::uint32_t>(std::strtoul(rate_text.c_str(), nullptr, 10));
    const auto channels =
        static_cast<std::uint32_t>(std::strtoul(channels_text.c_str(), nullptr, 10));
    if (rate == 0 || channels == 0 || sample_fmt.empty()) {
        return false;
    }

    out = Stream{};
    out.format.sample_rate = rate;
    out.format.channels = channels;
    out.format.channel_mask = 0;
    out.format.encoding = MP_ENCODING_PCM;

    // Ask for exactly what the decoder produces. Anything else would put a
    // converter in the chain, which is the one thing a decoder here must not do.
    const bool planar_or_flat_float =
        sample_fmt == "flt" || sample_fmt == "fltp" || sample_fmt == "dbl" ||
        sample_fmt == "dblp";
    const auto raw_bits =
        static_cast<std::uint32_t>(std::strtoul(raw_bits_text.c_str(), nullptr, 10));

    if (planar_or_flat_float) {
        // Vorbis, Opus and AAC decode to float natively. Saying so is honest;
        // pretending they are integers would be a conversion nobody asked for,
        // and the graph will route it to Path B or refuse, which is correct.
        //
        // Doubles are the exception, and they get said out loud. A 64-bit float
        // WAV really does hold more than MP_SAMPLE_F32 can carry, and this ABI
        // has no wider type -- so narrowing is the only way to play the file at
        // all, and the rule against converting inside a decoder means the
        // narrowing has to be visible rather than assumed.
        if (sample_fmt == "dbl" || sample_fmt == "dblp") {
            log_fmt(MP_LOG_WARN,
                    "%s holds 64-bit floats and is being narrowed to 32; the output is "
                    "not the file's own samples",
                    path);
        }
        out.format.sample_type = MP_SAMPLE_F32;
        out.format.valid_bits = 0;
        out.frame_bytes = 4 * channels;
        out.raw_format = L"f32le";
    } else if (sample_fmt == "s16" || sample_fmt == "s16p") {
        out.format.sample_type = MP_SAMPLE_S16;
        out.format.valid_bits = 16;
        out.frame_bytes = 2 * channels;
        out.raw_format = L"s16le";
    } else if (sample_fmt == "s32" || sample_fmt == "s32p") {
        if (raw_bits == 24) {
            out.format.sample_type = MP_SAMPLE_S24_PACKED;
            out.format.valid_bits = 24;
            out.frame_bytes = 3 * channels;
            out.raw_format = L"s24le";
        } else {
            out.format.sample_type = MP_SAMPLE_S32;
            out.format.valid_bits = 32;
            out.frame_bytes = 4 * channels;
            out.raw_format = L"s32le";
        }
    } else {
        log_fmt(MP_LOG_WARN,
                "no raw format matches FFmpeg's %s; refusing rather than letting it "
                "convert",
                sample_fmt.c_str());
        return false;
    }

    const double seconds = std::strtod(duration_text.c_str(), nullptr);
    out.total_frames = seconds > 0.0 ? static_cast<std::uint64_t>(seconds * rate) : 0;
    return true;
}

MpResult MP_CALL demux_open(const char* path, MpDemux** out) noexcept
try {
    if (path == nullptr || out == nullptr) {
        return MP_ERR_INVALID;
    }
    *out = nullptr;
    if (g_ffprobe.empty() || g_ffmpeg.empty()) {
        return MP_ERR_UNSUPPORTED;
    }

    const std::wstring wide_path = widen(path);
    if (wide_path.empty()) {
        return MP_ERR_INVALID;
    }

    // **Every audio stream, not the first one.** `-select_streams a` without an
    // index is the whole of the change, and it is what a container reader owed
    // the rest of the program: a file with a commentary track has two, and until
    // now one of them did not exist as far as MediaPerch was concerned.
    const std::wstring probe =
        quoted(g_ffprobe) +
        L" -v error -select_streams a"
        L" -show_entries stream=sample_rate,channels,sample_fmt,bits_per_raw_sample,duration"
        L" -of default=noprint_wrappers=0 " +
        quoted(wide_path);
    const std::string description = capture(probe);
    if (description.empty()) {
        return MP_ERR_UNSUPPORTED;
    }

    auto* d = new (std::nothrow) MpDemux();
    if (d == nullptr) {
        return MP_ERR_NO_MEMORY;
    }
    d->path = wide_path;
    for (const std::string& block : stream_blocks(description)) {
        Stream stream;
        if (describe(block, path, stream)) {
            d->streams.push_back(std::move(stream));
        }
    }
    if (d->streams.empty()) {
        delete d;
        return MP_ERR_UNSUPPORTED;
    }

    // The child is not started here. `select` is where a host says which stream
    // it wants, and starting FFmpeg before being told would mean starting it
    // twice for every file with more than one track.
    *out = d;
    return MP_OK;
} catch (...) {
    return MP_ERR_NO_MEMORY;
}

MpResult MP_CALL demux_stream_count(MpDemux* d, std::uint32_t* out_count) noexcept
{
    if (d == nullptr || out_count == nullptr) {
        return MP_ERR_INVALID;
    }
    *out_count = static_cast<std::uint32_t>(d->streams.size());
    return MP_OK;
}

MpResult MP_CALL demux_stream_info(MpDemux* d, std::uint32_t index, MpStreamInfo* out) noexcept
{
    if (d == nullptr || out == nullptr || index >= d->streams.size()) {
        return MP_ERR_INVALID;
    }
    const std::uint32_t size = out->size;
    std::memset(out, 0, size);
    out->size = size;
    out->index = index;
    out->kind = MP_STREAM_AUDIO;
    // **A declaration, not a disguise.** There is no seam inside FFmpeg that
    // this tree could take hold of: it is a file at one end and PCM at the
    // other. Saying MP_CODEC_INTERNAL is more honest than naming a codec and
    // then refusing to let anybody else decode it.
    out->codec = MP_CODEC_INTERNAL;
    out->flags = MP_STREAM_SELF_DECODES | (index == 0 ? MP_STREAM_DEFAULT : 0u);
    out->config_bytes = 0;
    out->format = d->streams[index].format;
    // From the container's duration, so it is close rather than exact. Nothing
    // depends on it being exact; the stream ending is what ends playback.
    out->total_frames = d->streams[index].total_frames;
    return MP_OK;
}

MpResult MP_CALL demux_stream_config(MpDemux* d, std::uint32_t index, std::uint8_t* out,
                                     std::uint32_t out_bytes,
                                     std::uint32_t* out_needed) noexcept
{
    (void)out;
    (void)out_bytes;
    if (d == nullptr || index >= d->streams.size() || out_needed == nullptr) {
        return MP_ERR_INVALID;
    }
    *out_needed = 0; // nothing to configure: no codec module is looked up
    return MP_OK;
}

MpResult MP_CALL demux_select_streams(MpDemux* d, const std::uint32_t* indices,
                                      std::uint32_t count) noexcept
{
    if (d == nullptr || indices == nullptr || count == 0) {
        return MP_ERR_INVALID;
    }
    // **This one is a child process decoding to a pipe**, so a second stream
    // would be a second `ffmpeg` and a second pipe rather than a second track
    // out of one read. Declining is not a limitation of the container.
    if (count > 1) {
        return MP_ERR_UNSUPPORTED;
    }
    if (indices[0] >= d->streams.size()) {
        return MP_ERR_INVALID;
    }
    d->selected = indices[0];
    return start_at(d, 0) ? MP_OK : MP_ERR_IO;
}

MpResult MP_CALL demux_read_packet(MpDemux* d, void* dst, std::size_t dst_bytes,
                                   MpPacket* out) noexcept
{
    (void)dst;
    (void)dst_bytes;
    if (d == nullptr || out == nullptr) {
        return MP_ERR_INVALID;
    }
    // Every stream here is MP_STREAM_SELF_DECODES, so there are no packets to
    // hand over. A host that asks anyway has misread the flag.
    out->bytes = 0;
    return MP_ERR_UNSUPPORTED;
}

MpResult MP_CALL demux_read_frames(MpDemux* d, void* dst, std::size_t dst_bytes,
                                   std::size_t* out_bytes) noexcept
try {
    if (d == nullptr || dst == nullptr || out_bytes == nullptr) {
        return MP_ERR_INVALID;
    }
    *out_bytes = 0;
    if (!d->started && !start_at(d, 0)) {
        return MP_ERR_IO;
    }
    if (!d->child.running() || d->ended) {
        return MP_END;
    }

    const std::uint32_t frame_bytes = d->current().frame_bytes;
    const std::size_t want = (dst_bytes / frame_bytes) * frame_bytes;
    if (want == 0) {
        return MP_OK;
    }

    std::size_t got = d->child.read(dst, want);
    got -= got % frame_bytes; // never hand back a partial frame
    if (got == 0) {
        d->ended = true;
        return MP_END;
    }

    d->position += got / frame_bytes;
    *out_bytes = got;
    return MP_OK;
} catch (...) {
    return MP_ERR_IO;
}

MpResult MP_CALL demux_seek(MpDemux* d, std::uint32_t stream,
                            std::uint64_t frame) noexcept
{
    if (d == nullptr || stream >= d->streams.size()) {
        return MP_ERR_INVALID;
    }
    // Seeking restarts the child. That is what going through the executables
    // costs, and it is a few tens of milliseconds rather than a correctness
    // problem -- the restart uses output-side -ss, which is sample-accurate, so
    // the host has nothing to discard afterwards and no MP_PACKET_TIMED to read.
    return start_at(d, frame) ? MP_OK : MP_ERR_IO;
}

void MP_CALL demux_close(MpDemux* d) noexcept
{
    delete d;
}

MpResult MP_CALL module_init(const MpHost* host) noexcept
{
    g_host = host;
    g_ffmpeg = find_program(L"ffmpeg.exe");
    g_ffprobe = find_program(L"ffprobe.exe");

    if (g_ffmpeg.empty() || g_ffprobe.empty()) {
        // Not an error. A module whose dependency is absent is a module that
        // declines every file, which is exactly what an uninstalled module does.
        log(MP_LOG_INFO,
            "no ffmpeg/ffprobe on PATH or beside the module; decode_ffmpeg will "
            "decline every file");
        return MP_OK;
    }
    log_fmt(MP_LOG_DEBUG, "using %s", narrow(g_ffmpeg).c_str());
    return MP_OK;
}

void MP_CALL module_shutdown() noexcept
{
    g_host = nullptr;
    g_ffmpeg.clear();
    g_ffprobe.clear();
}

const MpDemuxVtbl g_vtbl = {
    /* size          */ sizeof(MpDemuxVtbl),
    /* reserved      */ 0,
    /* probe         */ &demux_probe,
    /* open          */ &demux_open,
    /* stream_count  */ &demux_stream_count,
    /* stream_info   */ &demux_stream_info,
    /* stream_config */ &demux_stream_config,
    /* select_streams*/ &demux_select_streams,
    /* read_packet   */ &demux_read_packet,
    /* seek          */ &demux_seek,
    /* read_frames   */ &demux_read_frames,
    /* close         */ &demux_close,
    /* stream_video_info */ nullptr, // a pipeline, not a container reader
};

/// **The one this module will not claim to be a codec for.** Every stream it
/// produces is MP_STREAM_SELF_DECODES, so no codec is ever looked up for it and
/// naming any here would be a promise it does not keep.
const MpCodec g_codecs[] = {MP_CODEC_INTERNAL};

const MpModuleDesc g_desc = {
    /* size        */ sizeof(MpModuleDesc),
    /* abi_version */ MP_ABI_VERSION,
    /* flags       */ 0,
    /* version     */ MP_MAKE_VERSION(0, 1, 0),
    /* kind        */ MP_KIND_DEMUX,
    /* priority    */ 60, // the fallback everywhere except MP4 -- see demux_probe
    /* id          */ "demux_ffmpeg",
    /* name        */ "FFmpeg (found at run time, not shipped)",
    /* init        */ &module_init,
    /* shutdown    */ &module_shutdown,
    /* vtbl        */ &g_vtbl,
    /* codecs      */ g_codecs,
    /* codec_count */ 1,
    /* reserved    */ 0,
};

} // namespace

extern "C" MP_EXPORT const MpModuleDesc* MP_CALL mp_module_entry(std::uint32_t host_abi_version)
{
    if (host_abi_version != MP_ABI_VERSION) {
        return nullptr;
    }
    return &g_desc;
}
