// SPDX-License-Identifier: GPL-3.0-or-later
//
// The long tail, through whatever FFmpeg the machine already has.
//
// FFmpeg is the one dependency this tree does not vendor, and the reasons are
// concrete: its configure is a shell script needing MSYS2 and nasm on Windows,
// its build is tens of minutes, its output is tens of megabytes, and **whether
// it is LGPL or GPL is a choice that belongs to whoever installs it**. So this
// module finds it at run time and reports itself unable when it is absent, which
// is the behaviour the architecture already has for a module nobody installed.
//
// It talks to `ffprobe` and `ffmpeg` as programs rather than linking libavcodec,
// and that is deliberate rather than lazy. FFmpeg's public structs -- AVFrame,
// AVCodecContext, AVStream -- change layout between major versions, so resolving
// the symbols out of a DLL still leaves the struct layouts to get right, and the
// headers that describe them cannot be vendored on their own because `avconfig.h`
// is generated by configure. Going through the executables costs a process per
// file and buys immunity from all of that: this works against FFmpeg 4 through 8
// without being rebuilt.
//
// Bit-exactness is unaffected and is checked the same way as everywhere else:
// the raw format asked for is the decoder's own native one, and the bytes are
// hashed against a reference. See docs/formats.md.

#include <mediaperch/module.h>

#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <windows.h>

#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace {

const MpHost* g_host = nullptr;
std::wstring g_ffmpeg;
std::wstring g_ffprobe;

void log(MpLogLevel level, const char* message) noexcept
{
    if (g_host != nullptr && g_host->log != nullptr) {
        g_host->log(g_host->ctx, level, message);
    }
}

void log_fmt(MpLogLevel level, const char* format, ...) noexcept
{
    char buffer[1024];
    va_list args;
    va_start(args, format);
    std::vsnprintf(buffer, sizeof(buffer), format, args);
    va_end(args);
    log(level, buffer);
}

std::wstring widen(const char* utf8)
{
    if (utf8 == nullptr || *utf8 == '\0') {
        return {};
    }
    const int needed = ::MultiByteToWideChar(CP_UTF8, 0, utf8, -1, nullptr, 0);
    if (needed <= 1) {
        return {};
    }
    std::wstring out(static_cast<std::size_t>(needed - 1), L'\0');
    ::MultiByteToWideChar(CP_UTF8, 0, utf8, -1, out.data(), needed);
    return out;
}

std::string narrow(const std::wstring& wide)
{
    if (wide.empty()) {
        return {};
    }
    const int needed = ::WideCharToMultiByte(CP_UTF8, 0, wide.c_str(), -1, nullptr, 0,
                                             nullptr, nullptr);
    if (needed <= 1) {
        return {};
    }
    std::string out(static_cast<std::size_t>(needed - 1), '\0');
    ::WideCharToMultiByte(CP_UTF8, 0, wide.c_str(), -1, out.data(), needed, nullptr,
                          nullptr);
    return out;
}

/// Beside this module first, then wherever PATH says. Beside first so that an
/// install can ship a known FFmpeg without changing the machine's.
std::wstring find_program(const wchar_t* name)
{
    wchar_t module_path[MAX_PATH * 2]{};
    HMODULE self = nullptr;
    ::GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                             GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                         reinterpret_cast<LPCWSTR>(&find_program), &self);
    if (::GetModuleFileNameW(self, module_path, static_cast<DWORD>(std::size(module_path)))
        != 0) {
        std::wstring beside{module_path};
        const std::size_t slash = beside.find_last_of(L"\\/");
        if (slash != std::wstring::npos) {
            beside.resize(slash + 1);
            beside += name;
            if (::GetFileAttributesW(beside.c_str()) != INVALID_FILE_ATTRIBUTES) {
                return beside;
            }
        }
    }

    wchar_t found[MAX_PATH * 2]{};
    wchar_t* leaf = nullptr;
    const DWORD n = ::SearchPathW(nullptr, name, nullptr,
                                  static_cast<DWORD>(std::size(found)), found, &leaf);
    return (n != 0 && n < std::size(found)) ? std::wstring{found} : std::wstring{};
}

/// A child process whose stdout we read. stderr goes nowhere: FFmpeg writes
/// progress there and none of it is ours to interpret.
class Child {
public:
    Child() = default;
    ~Child() { close(); }
    Child(const Child&) = delete;
    Child& operator=(const Child&) = delete;
    Child(Child&&) = delete;
    Child& operator=(Child&&) = delete;

    bool start(const std::wstring& command_line)
    {
        close();

        SECURITY_ATTRIBUTES inheritable{};
        inheritable.nLength = sizeof(inheritable);
        inheritable.bInheritHandle = TRUE;

        HANDLE read_end = nullptr;
        HANDLE write_end = nullptr;
        if (::CreatePipe(&read_end, &write_end, &inheritable, 1 << 20) == 0) {
            return false;
        }
        // The read end must not travel into the child, or the pipe never reports
        // end-of-file because this process still holds a writer.
        ::SetHandleInformation(read_end, HANDLE_FLAG_INHERIT, 0);

        STARTUPINFOW startup{};
        startup.cb = sizeof(startup);
        startup.dwFlags = STARTF_USESTDHANDLES;
        startup.hStdOutput = write_end;
        startup.hStdError = ::GetStdHandle(STD_ERROR_HANDLE);
        startup.hStdInput = nullptr;

        PROCESS_INFORMATION process{};
        std::wstring mutable_command = command_line; // CreateProcessW may write to it
        const BOOL ok = ::CreateProcessW(nullptr, mutable_command.data(), nullptr, nullptr,
                                         TRUE, CREATE_NO_WINDOW, nullptr, nullptr,
                                         &startup, &process);
        ::CloseHandle(write_end);
        if (ok == 0) {
            ::CloseHandle(read_end);
            return false;
        }

        ::CloseHandle(process.hThread);
        process_ = process.hProcess;
        stdout_ = read_end;
        return true;
    }

    /// Blocks until `bytes` are read or the child closes its end.
    std::size_t read(void* dst, std::size_t bytes)
    {
        auto* out = static_cast<std::uint8_t*>(dst);
        std::size_t total = 0;
        while (total < bytes) {
            DWORD got = 0;
            const DWORD want =
                static_cast<DWORD>(bytes - total < (1u << 20) ? bytes - total : (1u << 20));
            if (::ReadFile(stdout_, out + total, want, &got, nullptr) == 0 || got == 0) {
                break;
            }
            total += got;
        }
        return total;
    }

    void close() noexcept
    {
        if (process_ != nullptr) {
            // Stopping mid-file is the normal case: the graph is done with the
            // track. Waiting for FFmpeg to finish decoding the rest of an album
            // side would be the strange behaviour.
            ::TerminateProcess(process_, 0);
            ::WaitForSingleObject(process_, 2000);
            ::CloseHandle(process_);
            process_ = nullptr;
        }
        if (stdout_ != nullptr) {
            ::CloseHandle(stdout_);
            stdout_ = nullptr;
        }
    }

    [[nodiscard]] bool running() const noexcept { return stdout_ != nullptr; }

private:
    HANDLE process_ = nullptr;
    HANDLE stdout_ = nullptr;
};

/// Runs a program to completion and returns everything it wrote to stdout.
std::string capture(const std::wstring& command_line)
{
    Child child;
    if (!child.start(command_line)) {
        return {};
    }
    std::string out;
    std::vector<char> chunk(64 * 1024);
    for (;;) {
        const std::size_t got = child.read(chunk.data(), chunk.size());
        if (got == 0) {
            break;
        }
        out.append(chunk.data(), got);
    }
    return out;
}

std::wstring quoted(const std::wstring& path)
{
    return L"\"" + path + L"\"";
}

/// ffprobe's `key=value` output, which exists precisely so that nobody has to
/// put a JSON parser in a decoder module.
std::string field(const std::string& text, const char* key)
{
    const std::string needle = std::string{key} + "=";
    std::size_t at = 0;
    while ((at = text.find(needle, at)) != std::string::npos) {
        const bool at_line_start = at == 0 || text[at - 1] == '\n' || text[at - 1] == '\r';
        if (at_line_start) {
            const std::size_t from = at + needle.size();
            const std::size_t to = text.find_first_of("\r\n", from);
            return text.substr(from, to == std::string::npos ? std::string::npos
                                                             : to - from);
        }
        at += needle.size();
    }
    return {};
}

bool magic(const std::uint8_t* head, std::size_t bytes, const char* what,
           std::size_t offset = 0)
{
    const std::size_t n = std::strlen(what);
    return bytes >= offset + n && std::memcmp(head + offset, what, n) == 0;
}

} // namespace

struct MpDecoder {
    std::wstring path;
    MpFormat format{};
    std::uint32_t frame_bytes = 0;
    std::uint64_t total_frames = 0;
    /// The raw muxer FFmpeg is asked for: exactly the decoder's own sample
    /// format, so that nothing in the chain converts.
    std::wstring raw_format;

    Child child;
    std::uint64_t position = 0;
    bool ended = false;
};

namespace {

bool start_at(MpDecoder* d, std::uint64_t frame)
{
    // -ss after -i is the sample-accurate form. The other one, before -i, seeks
    // by container index and lands on a packet boundary, which is faster and
    // wrong for a player that reports positions in frames.
    std::wstring command = quoted(g_ffmpeg) + L" -v error -nostdin -i " + quoted(d->path);
    if (frame != 0) {
        const double seconds = static_cast<double>(frame) / d->format.sample_rate;
        wchar_t at[64]{};
        std::swprintf(at, std::size(at), L" -ss %.9f", seconds);
        command += at;
    }
    command += L" -map 0:a:0 -f " + d->raw_format + L" -";

    d->position = frame;
    d->ended = false;
    return d->child.start(command);
}

MpResult MP_CALL decoder_probe(const char* path, const std::uint8_t* head, std::size_t bytes,
                               std::uint32_t* out_score) noexcept
{
    if (out_score == nullptr) {
        return MP_ERR_INVALID;
    }
    (void)path;
    *out_score = 0;
    if (head == nullptr || g_ffprobe.empty()) {
        return MP_OK; // nothing installed to decode with
    }

    // The formats nothing else in this tree reads. Scored at 100 because for
    // these it is the only answer; everything else gets 30, so it stays the
    // fallback rather than taking work from a decoder that does it better.
    static const struct {
        const char* bytes;
        std::size_t at;
    } only_here[] = {
        {"OggS", 0},                     // Vorbis, Opus, Speex
        {"MAC ", 0},                     // Monkey's Audio
        {"wvpk", 0},                     // WavPack
        {"\x1A\x45\xDF\xA3", 0},         // Matroska, WebM
        {"DSD ", 0},                     // DSF
        {"FRM8", 0},                     // DFF
        {"TTA1", 0},                     // True Audio
        {"MPCK", 0},                     // Musepack
        {"caff", 0},                     // Core Audio Format
    };

    for (const auto& candidate : only_here) {
        if (magic(head, bytes, candidate.bytes, candidate.at)) {
            *out_score = 100;
            return MP_OK;
        }
    }
    if (magic(head, bytes, "ftyp", 4) || magic(head, bytes, "ID3") ||
        magic(head, bytes, "fLaC") || magic(head, bytes, "RIFF") ||
        (bytes >= 2 && head[0] == 0xFF && (head[1] & 0xE0) == 0xE0)) {
        *out_score = 30;
    }
    return MP_OK;
}

MpResult MP_CALL decoder_open(const char* path, MpDecoder** out) noexcept
try {
    if (path == nullptr || out == nullptr) {
        return MP_ERR_INVALID;
    }
    *out = nullptr;
    if (g_ffprobe.empty() || g_ffmpeg.empty()) {
        return MP_ERR_UNSUPPORTED;
    }

    const std::wstring wide_path = widen(path);
    if (wide_path.empty()) {
        return MP_ERR_INVALID;
    }

    const std::wstring probe =
        quoted(g_ffprobe) +
        L" -v error -select_streams a:0"
        L" -show_entries stream=sample_rate,channels,sample_fmt,bits_per_raw_sample,duration"
        L" -of default=noprint_wrappers=1 " +
        quoted(wide_path);
    const std::string description = capture(probe);
    if (description.empty()) {
        return MP_ERR_UNSUPPORTED;
    }

    const std::string rate_text = field(description, "sample_rate");
    const std::string channels_text = field(description, "channels");
    const std::string sample_fmt = field(description, "sample_fmt");
    const std::string raw_bits_text = field(description, "bits_per_raw_sample");
    const std::string duration_text = field(description, "duration");

    const auto rate = static_cast<std::uint32_t>(std::strtoul(rate_text.c_str(), nullptr, 10));
    const auto channels =
        static_cast<std::uint32_t>(std::strtoul(channels_text.c_str(), nullptr, 10));
    if (rate == 0 || channels == 0 || sample_fmt.empty()) {
        return MP_ERR_UNSUPPORTED;
    }

    auto decoder = new MpDecoder{};
    decoder->path = wide_path;
    decoder->format.sample_rate = rate;
    decoder->format.channels = channels;
    decoder->format.channel_mask = 0;
    decoder->format.encoding = MP_ENCODING_PCM;

    // Ask for exactly what the decoder produces. Anything else would put a
    // converter in the chain, which is the one thing a decoder here must not do.
    const bool planar_or_flat_float =
        sample_fmt == "flt" || sample_fmt == "fltp" || sample_fmt == "dbl" ||
        sample_fmt == "dblp";
    const auto raw_bits =
        static_cast<std::uint32_t>(std::strtoul(raw_bits_text.c_str(), nullptr, 10));

    if (planar_or_flat_float) {
        // Vorbis, Opus and AAC decode to float natively. Saying so is honest;
        // pretending they are integers would be a conversion nobody asked for,
        // and the graph will route it to Path B or refuse, which is correct.
        decoder->format.sample_type = MP_SAMPLE_F32;
        decoder->format.valid_bits = 0;
        decoder->frame_bytes = 4 * channels;
        decoder->raw_format = L"f32le";
    } else if (sample_fmt == "s16" || sample_fmt == "s16p") {
        decoder->format.sample_type = MP_SAMPLE_S16;
        decoder->format.valid_bits = 16;
        decoder->frame_bytes = 2 * channels;
        decoder->raw_format = L"s16le";
    } else if (sample_fmt == "s32" || sample_fmt == "s32p") {
        if (raw_bits == 24) {
            decoder->format.sample_type = MP_SAMPLE_S24_PACKED;
            decoder->format.valid_bits = 24;
            decoder->frame_bytes = 3 * channels;
            decoder->raw_format = L"s24le";
        } else {
            decoder->format.sample_type = MP_SAMPLE_S32;
            decoder->format.valid_bits = 32;
            decoder->frame_bytes = 4 * channels;
            decoder->raw_format = L"s32le";
        }
    } else {
        log_fmt(MP_LOG_WARN, "no raw format matches FFmpeg's %s; refusing rather than "
                             "letting it convert",
                sample_fmt.c_str());
        delete decoder;
        return MP_ERR_UNSUPPORTED;
    }

    const double seconds = std::strtod(duration_text.c_str(), nullptr);
    decoder->total_frames =
        seconds > 0.0 ? static_cast<std::uint64_t>(seconds * rate) : 0;

    if (!start_at(decoder, 0)) {
        delete decoder;
        return MP_ERR_IO;
    }

    *out = decoder;
    return MP_OK;
} catch (...) {
    return MP_ERR_NO_MEMORY;
}

MpResult MP_CALL decoder_get_format(MpDecoder* d, MpFormat* out) noexcept
{
    if (d == nullptr || out == nullptr) {
        return MP_ERR_INVALID;
    }
    *out = d->format;
    return MP_OK;
}

MpResult MP_CALL decoder_get_length(MpDecoder* d, std::uint64_t* out_frames) noexcept
{
    if (d == nullptr || out_frames == nullptr) {
        return MP_ERR_INVALID;
    }
    // From the container's duration, so it is close rather than exact. Nothing
    // depends on it being exact; the stream ending is what ends playback.
    *out_frames = d->total_frames;
    return MP_OK;
}

MpResult MP_CALL decoder_read(MpDecoder* d, void* dst, std::size_t dst_bytes,
                              std::size_t* out_bytes) noexcept
try {
    if (d == nullptr || dst == nullptr || out_bytes == nullptr) {
        return MP_ERR_INVALID;
    }
    *out_bytes = 0;
    if (!d->child.running() || d->ended) {
        return MP_END;
    }

    const std::size_t want = (dst_bytes / d->frame_bytes) * d->frame_bytes;
    if (want == 0) {
        return MP_OK;
    }

    std::size_t got = d->child.read(dst, want);
    got -= got % d->frame_bytes; // never hand back a partial frame
    if (got == 0) {
        d->ended = true;
        return MP_END;
    }

    d->position += got / d->frame_bytes;
    *out_bytes = got;
    return MP_OK;
} catch (...) {
    return MP_ERR_IO;
}

MpResult MP_CALL decoder_seek(MpDecoder* d, std::uint64_t frame) noexcept
{
    if (d == nullptr) {
        return MP_ERR_INVALID;
    }
    // Seeking restarts the child. That is what going through the executables
    // costs, and it is a few tens of milliseconds rather than a correctness
    // problem -- the restart uses output-side -ss, which is sample-accurate.
    return start_at(d, frame) ? MP_OK : MP_ERR_IO;
}

void MP_CALL decoder_close(MpDecoder* d) noexcept
{
    delete d;
}

MpResult MP_CALL module_init(const MpHost* host) noexcept
{
    g_host = host;
    g_ffmpeg = find_program(L"ffmpeg.exe");
    g_ffprobe = find_program(L"ffprobe.exe");

    if (g_ffmpeg.empty() || g_ffprobe.empty()) {
        // Not an error. A module whose dependency is absent is a module that
        // declines every file, which is exactly what an uninstalled module does.
        log(MP_LOG_INFO,
            "no ffmpeg/ffprobe on PATH or beside the module; decode_ffmpeg will "
            "decline every file");
        return MP_OK;
    }
    log_fmt(MP_LOG_DEBUG, "using %s", narrow(g_ffmpeg).c_str());
    return MP_OK;
}

void MP_CALL module_shutdown() noexcept
{
    g_host = nullptr;
    g_ffmpeg.clear();
    g_ffprobe.clear();
}

const MpDecoderVtbl g_decoder_vtbl = {
    /* size       */ sizeof(MpDecoderVtbl),
    /* reserved   */ 0,
    /* probe      */ &decoder_probe,
    /* open       */ &decoder_open,
    /* get_format */ &decoder_get_format,
    /* get_length */ &decoder_get_length,
    /* read       */ &decoder_read,
    /* seek       */ &decoder_seek,
    /* close      */ &decoder_close,
};

const MpModuleDesc g_desc = {
    /* size        */ sizeof(MpModuleDesc),
    /* abi_version */ MP_ABI_VERSION,
    /* flags       */ 0,
    /* version     */ MP_MAKE_VERSION(0, 1, 0),
    /* kind        */ MP_KIND_DECODER,
    /* priority    */ 30, // the fallback: everything else knows its formats better
    /* id          */ "decode_ffmpeg",
    /* name        */ "FFmpeg (found at run time, not shipped)",
    /* init        */ &module_init,
    /* shutdown    */ &module_shutdown,
    /* vtbl        */ &g_decoder_vtbl,
};

} // namespace

extern "C" MP_EXPORT const MpModuleDesc* MP_CALL mp_module_entry(std::uint32_t host_abi_version)
{
    if (host_abi_version != MP_ABI_VERSION) {
        return nullptr;
    }
    return &g_desc;
}
