// SPDX-License-Identifier: GPL-3.0-or-later
//
// The constant tables of AAC, declared. `aac_tables.cpp` is generated by
// tools/gen_aac_tables.py and holds the values.
//
// These are ISO/IEC 14496-3's numbers, not anybody's design: the eleven
// spectrum Huffman codebooks, the scalefactor codebook, the scalefactor band
// offsets for each sample rate, and the TNS band limits. Every AAC decoder that
// exists contains the same ones. They are transcribed by a script rather than by
// hand so the provenance is checkable, and the generator refuses to write the
// file unless every codebook satisfies the Kraft equality -- which is what
// catches a truncated or mis-parsed table straight away instead of as quiet
// distortion three layers further down.

#ifndef MEDIAPERCH_AAC_TABLES_HPP
#define MEDIAPERCH_AAC_TABLES_HPP

#include <cstdint>

namespace mp::aac {

/// The eleven spectrum codebooks, as the standard gives them: a codeword and
/// its length per index. A decoding structure is built from these at init
/// rather than stored, so what ships is the standard's data and not a
/// particular decoder's idea of how to search it.
extern const std::uint16_t* const k_spectral_codes[11];
extern const std::uint8_t* const k_spectral_bits[11];
extern const std::uint16_t k_spectral_sizes[11];

/// The scalefactor codebook: 121 entries covering deltas of -60..+60.
extern const std::uint32_t k_scalefactor_code[121];
extern const std::uint8_t k_scalefactor_bits[121];

/// Scalefactor band offsets, indexed by the sample-rate index from the
/// AudioSpecificConfig. `_1024` is for long windows, `_128` for the eight short
/// ones; `k_num_swb_*` says how many bands each has.
extern const std::uint16_t* const k_swb_offset_1024[13];
extern const std::uint16_t* const k_swb_offset_128[13];
extern const std::uint8_t k_num_swb_1024[13];
extern const std::uint8_t k_num_swb_128[13];

/// The highest scalefactor band TNS may filter, per sample rate.
extern const std::uint8_t k_tns_max_bands_1024[13];
extern const std::uint8_t k_tns_max_bands_128[13];

} // namespace mp::aac

#endif // MEDIAPERCH_AAC_TABLES_HPP
