#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Transcribe SSRC's noise-shaping coefficients into this tree.

The psychoacoustically weighted shaping curves are measured tables, not
expressions: there is nothing to derive and everything to mistype. So they
arrive the way the AAC Huffman tables arrived -- from a named source, through a
generator that refuses to write a table failing its own checks, with the source
recorded in the output.

    Source:  https://github.com/shibatch/ssrc
             src/include/shibatch/shapercoefs.h
             "Noise shaper coefficients for SSRC, written by Naoki Shibata"
    Licence: Boost Software License 1.0, which is GPL-3.0 compatible.

The curves are ATH-weighted -- the absolute threshold of hearing -- which is why
they are indexed by sample rate as well as by intensity: where the ear stops
listening is a fixed frequency, and where that frequency sits in the spectrum
depends on how fast the samples go past.

Usage:
    python tools/gen_shaper_tables.py path/to/shapercoefs.h
"""
import io
import re
import sys

ENTRY = re.compile(
    r'\{\s*(\d+)\s*,\s*(\d+)\s*,\s*"([^"]*)"\s*,\s*(\d+)\s*,\s*\{([^}]*)\}[^}]*\}',
    re.S)

# Just the head of an entry, used only to count how many there are. Two of them
# carry a trailing comment between the closing braces, which the full pattern
# did not allow -- so it parsed 65 of 67 and said nothing. A generator that
# silently writes most of a table is worse than one that crashes, which is what
# this exists to make impossible.
HEAD = re.compile(r'\{\s*\d+\s*,\s*\d+\s*,\s*"[^"]*"\s*,\s*\d+\s*,')

# A coefficient far outside this is not a shaper, it is a transcription error.
# SSRC's own curves sit well inside it; the check is here to catch a parse that
# ran off the end of an entry, which is the failure mode that produces numbers
# that look almost right.
K_BOUND = 16.0


def parse(text):
    out = []
    expected = len(HEAD.findall(text))
    for rate, intensity, name, length, body in ENTRY.findall(text):
        coefs = [float(x) for x in re.findall(r'-?\d+\.?\d*(?:[eE][-+]?\d+)?', body)]
        rate, intensity, length = int(rate), int(intensity), int(length)
        # The arrays are a fixed size and `len` says how much of one is real;
        # the rest is zero padding. Taking the whole array would hand the filter
        # taps that are not part of the curve, so the pad is checked and
        # dropped rather than trusted.
        if len(coefs) < length:
            raise SystemExit(
                'entry %d/%d "%s" declares %d coefficients and has %d'
                % (rate, intensity, name, length, len(coefs)))
        if any(c != 0.0 for c in coefs[length:]):
            raise SystemExit(
                'entry %d/%d "%s" has a non-zero value past its declared length'
                % (rate, intensity, name))
        coefs = coefs[:length]
        for c in coefs:
            if not (-K_BOUND < c < K_BOUND):
                raise SystemExit('entry %d/%d "%s" has a coefficient of %g'
                                 % (rate, intensity, name, c))
        out.append((rate, intensity, name, coefs))

    if len(out) != expected:
        raise SystemExit('the file has %d entries and only %d parsed' %
                         (expected, len(out)))
    return out


HEADER = '''// SPDX-License-Identifier: GPL-3.0-or-later
//
// GENERATED by tools/gen_shaper_tables.py. Do not edit.
//
// Noise-shaping coefficients from SSRC, https://github.com/shibatch/ssrc,
// written by Naoki Shibata and licensed under the Boost Software License 1.0.
// They are transcribed rather than derived: these are measured curves weighted
// by the absolute threshold of hearing, which is also why they are indexed by
// sample rate -- where the ear stops listening is a fixed frequency, and where
// that sits in the spectrum depends on how fast the samples go past.
//
// %d curves, %d sample rates, %d coefficients in total.

#include "mediaperch/shaper_tables.hpp"

namespace mp {
namespace {

const double k_coefficients[] = {
'''


def emit(entries, path):
    flat = []
    spans = []
    for _rate, _intensity, _name, coefs in entries:
        spans.append((len(flat), len(coefs)))
        flat.extend(coefs)

    rates = sorted({e[0] for e in entries})
    body = io.StringIO()
    body.write(HEADER % (len(entries), len(rates), len(flat)))
    for i in range(0, len(flat), 3):
        body.write('    ' + ' '.join('%.20g,' % v for v in flat[i:i + 3]) + '\n')
    body.write('};\n\nconst ShaperCurve k_curves[] = {\n')
    for (rate, intensity, name, coefs), (at, n) in zip(entries, spans):
        body.write('    {%d, %d, "%s", k_coefficients + %d, %d},\n'
                   % (rate, intensity, name.replace('"', ''), at, n))
    body.write('};\n\n} // namespace\n\n')
    body.write('''std::span<const ShaperCurve> shaper_curves() noexcept
{
    return std::span<const ShaperCurve>{k_curves, std::size(k_curves)};
}

} // namespace mp
''')
    io.open(path, 'w', encoding='utf-8', newline='\n').write(body.getvalue())


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    entries = parse(io.open(sys.argv[1], encoding='utf-8', errors='replace').read())
    if not entries:
        raise SystemExit('no coefficient tables found in %s' % sys.argv[1])

    # Every curve must name a length that matches, which parse() checked, and
    # the set must cover the rates a decoder in this tree can produce. 44.1 and
    # 48 are the ones that matter; the check is that they are there at all.
    rates = {e[0] for e in entries}
    for needed in (44100, 48000):
        if needed not in rates:
            raise SystemExit('no curves for %d Hz' % needed)

    out = 'src/core/mediaperch/shaper_tables.cpp'
    emit(entries, out)
    print('%s: %d curves over %d rates, %d coefficients'
          % (out, len(entries), len(rates), sum(len(e[3]) for e in entries)))


if __name__ == '__main__':
    main()
